name: GHCR Docker Image
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  ORG: outposts-project

jobs:
  build-g3proxy:
    name: Build G3Proxy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: 'g3proxy/docker/alpine.Dockerfile'
          push: true
          tags: 'ghcr.io/${{ env.ORG }}/g3proxy:latest'
          cache-from: type=gha
          cache-to: type=gha,mode=max